### ISSUE TITLE
also look for README.rst along with README

### ISSUE THREAD

**Issue by jameshowison** [Impactstory/citeas-api#1]
just happened to see this today, I guess look for any file that starts with README ...  README.rst is "reStructured Text", an alternative to markdown ...

**Comment by hpiwowar** [comment]
yup!  We should be doing that now :)  README.*  Do you have an example where we are missing the readme?  That'll help us debug.  Thanks :)

**Comment by jameshowison** [comment]
http://citeas.org/cite/https://github.com/MDAnalysis/mdanalysis

**Comment by hpiwowar** [comment]
Thanks!
Heather

--
Heather Piwowar
cofounder of Impactstory <http://impactstory.org/>: share the full story of
your research impact.
  working from Vancouver, Canada
@researchremix <http://twitter.com/#!/researchremix> and @Impactstory
<https://twitter.com/ImpactStory>

**Comment by hpiwowar** [comment]
fixed!  :)
