### ISSUE TITLE
Support for Bioconductor packages?

### ISSUE THREAD

**Issue by DarwinAwardWinner** [Impactstory/citeas-api#12]
Many Bioconductor packages have a citation listed on their page, e.g. http://bioconductor.org/packages/release/bioc/html/edgeR.html

But CiteAs doesn't know how to find these. Each Bioconductor package page also has a DOI link, which pretty much just acts as a permalink to the same package page. I think this might be what CiteAs finds.

**Comment by hpiwowar** [comment]
I'm not familiar with Bioconductor.  Are the packages open source?  Is there source somewhere on the web from edgeR where they specify in a structured way that their preferred citation is as below, that the http://bioconductor.org/packages site uses to generate their webpage?   I tried looking here but it doesn't seem to be the right place:  https://git.bioconductor.org/packages/edgeR
Thanks!

```
Robinson MD, McCarthy DJ and Smyth GK (2010). “edgeR: a Bioconductor package for differential expression analysis of digital gene expression data.” Bioinformatics, 26(1), pp. 139-140.

McCarthy, J. D, Chen, Yunshun, Smyth and K. G (2012). “Differential expression analysis of multifactor RNA-Seq experiments with respect to biological variation.” Nucleic Acids Research, 40(10), pp. 4288-4297.

```

**Comment by DarwinAwardWinner** [comment]
Yes, all Bioconductor packages are open source. You found the correct git URL, but it is not a webpage. You would need to `git clone` it. Within each package repository is a file named `inst/CITATION` which contains the citation information for that package. However, you wouldn't typically access this file directly. Instead, you would start an R session, load the package, and then use R's `citation` function to display the citation for a package. The information page I linked to mentions this fact above the citation itself. For example:

```
$ R
> library(edgeR)
> toBibtex(citation("edgeR"))
@Article{,
  title = {edgeR: a Bioconductor package for differential expression analysis of digital gene expression data},
  author = {Mark D Robinson and Davis J McCarthy and Gordon K Smyth},
  journal = {Bioinformatics},
  volume = {26},
  number = {1},
  pages = {139-140},
  year = {2010},
}

@Article{,
  author = {{McCarthy} and Davis J. and {Chen} and {Yunshun} and {Smyth} and Gordon K.},
  title = {Differential expression analysis of multifactor RNA-Seq experiments with respect to biological variation},
  year = {2012},
  journal = {Nucleic Acids Research},
  volume = {40},
  number = {10},
  pages = {4288-4297},
}
```

I don't know if there is a way to get at that bibtex entry without running R and installing the package. However, you don't necessarily need to go that far. Every Bioconductor package page has a DOI at the top, which simply resolves to a permalink URL to that package. As an automated tool, it would probably be acceptable if CiteAs returned the metadata associated with this DOI as the citation, even if the package page itself lists an actual publication.

However, looking at the CiteAs output for https://bioconductor.org/packages/release/bioc/html/edgeR.html, I see:

```

Looking in the user input, we found a link to a
webpage
https://bioconductor.org/packages/release/bioc/html/edgeR.html

Looking in the webpage, we didn't find a link to a
GitHub repository main page

Looking in the webpage, we didn't find a DOI.
DOI API response

Looking in the webpage, we didn't find
BibTeX

Parsing the webpage, we found
The citation metadata
```

This means that CiteAs is not even finding the DOI listed at the top of the page. If I manually enter this DOI into CiteAs, I get a much more useful result. I think the easy short term fix is to just make sure CiteAs can find this DOI. Once that is done, then we can worry about the citation section below.

**Comment by DarwinAwardWinner** [comment]
As a note, the Bioconductor project has only recently switched from SVN to Git. There may be future plans for web-browseable Git mirrors, which would make it easier to get the CITATION file from the repo without cloning the entire thing.

**Comment by hpiwowar** [comment]
Fixed!  It now finds the DOI, as you suggested:  http://citeas.org/cite/https://bioconductor.org/packages/release/bioc/html/edgeR.html

Yes, I think we'll wait a bit and see if there is a browesable Git mirror to see if we can get the inst/CITATION file, like we do with CRAN.  

Thanks a lot for the detailed bug report and suggestions!

**Comment by DarwinAwardWinner** [comment]
I asked in the bioc-devel list, and here's the thread, with some ideas: https://stat.ethz.ch/pipermail/bioc-devel/2018-April/013296.html
