### ISSUE TITLE
Arxiv identifiers?

### ISSUE THREAD

**Issue by jameshowison** [Impactstory/citeas-api#17]
Can we recognize ArXiv identifiers?

eg:
arXiv:1802.02689

**Comment by hpiwowar** [comment]
great idea.

**Comment by hpiwowar** [comment]
anyone have an example where a request to cite is made using an arxiv identifier?

**Comment by jameshowison** [comment]
Yes, I had in mind an arvix identifier rather than name of software or URL
as starting point.

**Comment by hpiwowar** [comment]
great!  we can do that.  on it :)

**Comment by jameshowison** [comment]
Woohoo, you are fixing all the things!

**Comment by hpiwowar** [comment]
works!  http://citeas.org/cite/arXiv:1802.02689

:)
