### ISSUE TITLE
Support formatted CITATION files?

### ISSUE THREAD

**Issue by sdruskat** [Impactstory/citeas-api#18]
This is as opposed to free form CITATION files.

@ethanwhite notes in #6:

> There does appear to be quite a lot of variation [in CITATION files], [...] which maybe makes them difficult to use, but I thought I'd mention it. It might be possible to at least look for a bibtex citation inside the files.

I'm working on a solution for that in https://github.com/citation-file-format/. Happy to look into how CiteAs might be able to pick these up. Let me know if there is interest for this.

**Comment by hpiwowar** [comment]
Definitely interest in that.  Can you send us links to two github repos using the new format (when that happens) and then we'll get on implementing support.  The links help with our testing :)  Thanks!

**Comment by sdruskat** [comment]
@hpiwowar *Finally* got round to sending you links (via email), sorry for the delay. Thanks for your support and let me know if I can help with anything.

**Comment by hpiwowar** [comment]
From email:

Here are some repos that contain CITATION.cff files.
The very first one is a key-complete example file, so probably nothing
that you would encounter in the wild, but could perhaps help with
implementing support. The others are real files by real people.

- https://github.com/citation-file-format/schema/blob/master/CFF-Core/CITATION.cff
- https://github.com/AA-ALERT/frbcatdb/blob/master/CITATION.cff
- https://github.com/3D-e-Chem/knime-pharmacophore/blob/master/CITATION.cff
- https://github.com/CLARIAH/grlc/blob/master/CITATION.cff

**Comment by hpiwowar** [comment]
These are all working now.  Thanks :)

http://citeas.org/cite/https://github.com/CLARIAH/grlc
http://citeas.org/cite/https://github.com/3D-e-Chem/knime-pharmacophore
http://citeas.org/cite/https://github.com/AA-ALERT/frbcatdb

**Comment by sdruskat** [comment]
Hi @hpiwowar, great, thanks! Has this been deployed already? I'm getting "Sorry, we weren't able to figure out ..." pages for all three examples?

**Comment by hpiwowar** [comment]
whoops!  I pushed a bug last night that broke many things.  sorry about that, fixed now!
