### ISSUE TITLE
emcee has bibtex request on README that we don't find

### ISSUE THREAD

**Issue by jameshowison** [Impactstory/citeas-api#19]
At URSSI.  package "emcee" first we don't find the github repo.

But if I use the URL  https://github.com/dfm/emcee for the package, it finds the README but doesn't seem to find the request  (Heading "Attribution" then bibtex in a code block. It also has the text "Please cite" on the page.  

Seems like we should be able to get that one.

**Comment by hpiwowar** [comment]
Fixed!  http://citeas.org/cite/https://github.com/dfm/emcee

:)
