### ISSUE TITLE
CITATION file not found for Py6S

### ISSUE THREAD

**Issue by robintw** [Impactstory/citeas-api#21]
I have a CITATION file for my project Py6S, in the root of the Github repo (https://github.com/robintw/Py6S/blob/master/CITATION), however, citeas doesn't seem to find anything (see http://citeas.org/cite/https://github.com/robintw/Py6S).

By the way, I'm the author of the original blog post on using CITATION files outside of R - and it's great to see them being used in this way!

**Comment by hpiwowar** [comment]
Fixed!  http://citeas.org/cite/https://github.com/robintw/Py6S

Thanks again for the bug report :)
