### ISSUE TITLE
not finding codemeta

### ISSUE THREAD

**Issue by hpiwowar** [Impactstory/citeas-api#22]
(from Steven G. Johnson in email)

I tried
	http://fftw.org/
and citeas.org said

We weren't able to figure out a citation for this research product. We're in active development and hopefully this particular case will be working soon. Feel free to let us know and we'll look into it.

fftw.org links to a github page (https://github.com/FFTW/fftw3) that has a codemeta.json file (albeit added only recently), so my understanding was that your algorithms should be able to figure it out.

I checked, and the codemeta.json file had a typo (a stray comma) that made it invalid JSON.   That has now been fixed, but citeas.org still returns an error, making me suspect that it is using a cached result.

Two suggestions:

• Give a more descriptive error message if an invalid codemeta.json file is found.

• If you are caching, document a way to force citeas.org to reload the codemeta.json file in case of changes.

**Comment by hpiwowar** [comment]
fixed!  http://citeas.org/cite/http://fftw.org/

We had a bug in our codemeta file parsing such that it was breaking even with valid JSON.  We haven't seen very many of these in the wild yet, so still improving.  We aren't caching, was just a parsing bug.

Agreed about more descriptive error messages being useful.  Will work on that.

Thanks a lot for the bug report!  It's a really cool example... adding to our README so other people can try it out too :)

**Comment by stevengj** [comment]
I just tried it and it still gives me the same error message for http://citeas.org/cite/http://fftw.org/

**Comment by hpiwowar** [comment]
Sorry about that!  I pushed a bug.  Fixed now :)
