### ISSUE TITLE
Trying to identify why citation isn't being generated

### ISSUE THREAD

**Issue by npch** [Impactstory/citeas-api#27]
I'm trying to find out why a citation isn't being generated by CiteAs for the following repository:

https://github.com/softwaresaved/code-cite

which contains both a codemeta.json file and a DOI in the README.md.

Is there a way of turning a "verbose" mode on in the CiteAs.org hosted webapp?

**Comment by hpiwowar** [comment]
Hi Neil, 
It looks like we are throwing an exception for some reason.  We'll update the "cant' find a citation" message to say we have bug, that'll be a lot more clear.
And also fix the bug :)

Thanks for the bug report!

**Comment by npch** [comment]
Thanks @hpiwowar!

**Comment by caseydm** [comment]
Hi Neal. This should be showing up correctly now based on the codemeta.json file. I think a future improvement is to grab the DOI badge as well and combine the two sources. Please take a look. If it's not correct we can reopen the issue.
