### ISSUE TITLE
Broken example on examples page (FeedVis)

### ISSUE THREAD

**Issue by jameshowison** [Impactstory/citeas-api#29]
http://citeas.org/cite/https://github.com/jasonpriem/FeedVis is on the examples README but doesn't seem to work.

**Comment by hpiwowar** [comment]
workaround fix done.  looks like it has a bug in github repo call though... have to look into this.

**Comment by caseydm** [comment]
Hi James. I updated the code to match changes to Github's API format so that link is working properly now.
