### ISSUE TITLE
Zenodo URLs resolve to (wrong) github URL, instead of Zenodo DOI

### ISSUE THREAD

**Issue by cboettig** [Impactstory/citeas-api#41]
Since DOIs are redirects, it would be nice if CiteAs could "reverse" that process to always resolve the DOI.  Often this works already (JOSS), but on Zenodo this fails, sometimes dramatically: e.g. http://citeas.org/cite/https://zenodo.org/record/1442365%23.XEi7S89KjEY resolves to Zenodo, but then resolves to the wrong GitHub URL!  (If it found the right URL, it would have found the right codemeta.json and actually gotten a better citation than the one on Zenodo, but seems like resolving to the Zenodo DOI should take priority here).

**Comment by cboettig** [comment]
As @lnielsen pointed out today, from the Zenodo HTML you can actually pull the JSON-LD directly which will give a better source for the citation (including resolving the DOI).  I think you can request the JSON-LD directly from the same URL via content negotiation headers(?)

**Comment by caseydm** [comment]
Ok, URLs of type https://zenodo.org/record/1442365 are now resolved to DOIs very early in the process. 

Pulling the citation from JSON-LD is interesting, and I did see it available in the document. But right now the software is designed to prioritize DOIs and crossref. I'll discuss the concept though and consider adding that down the road.

**Comment by cboettig** [comment]
Very nice!
