### ISSUE TITLE
map non-URL (eg software name) to first URL in google results?

### ISSUE THREAD

**Issue by jameshowison** [Impactstory/citeas-api#44]
I think it would be a simple addition, and very useful, to map from words to URLs via the first (or first few) URLs that show up in a websearch (with adding the word "software").

e.g., Giovanni --> https://www.google.com/search?q=giovanni+software --> https://giovanni.gsfc.nasa.gov/giovanni/

Thoughts?

**Comment by caseydm** [comment]
I think this is a great idea. I was able to implement it, and set it as a last resort after trying DOI, github, arvix, cran, etc.
