### ISSUE TITLE
Make more explicit whether the citation is requested by creators or generated by CiteAs

### ISSUE THREAD

**Issue by AlastairKelly** [Impactstory/citeas-api#48]
Hi! My project team is using CiteAs while we review literature for reproducibility practices. One of the things we are looking at is whether software creators request a citation--your tool quite is helpful in finding these. However, the provenance statements don't always make it totally clear to us as naive users in which cases the citation is something the creators actually requested/confirmed as the preferred way to cite versus cases where your tool is making a suggestion based on whatever metadata it can scrape into an ad hoc suggestion. It would be great for the wording to make this more obvious. Thanks!

**Comment by caseydm** [comment]
Hello! At this time the software is not finding or parsing when authors say something like 'Please cite this project as'. Rather, it goes through a hierarchy of likely citation data and stops when it finds one. But most of those sources, such as a DOI or CITATION file were put in place by the authors so the citation should be close to what they want.

Sources are not mixed together. So in [this](http://citeas.org/cite/http://yt-project.org) example, when the DOI is found, the entire citation is made from the DOI. Whether the author prefers the DOI as the ideal source, we do not know. Does that make sense?
