### ISSUE TITLE
explaining

### ISSUE THREAD

**Issue by danielskatz** [Impactstory/citeas-api#5]
You might also want to say that one of the side affects of this will be to push codemeta, since if the developers are unhappy with the cite that is generated, adding that file will be the simplest way to generate something they like better.  This also implies that you might want to provide instructions on how to do this, or even tools to make it easy.

**Comment by hpiwowar** [comment]
Great points!  Added here, as a motivation for the project, and instructions for authors:  http://citeas.org/modify-your-citation
