### ISSUE TITLE
api.citeas.org needs to be HTTPS

### ISSUE THREAD

**Issue by hubgit** [Impactstory/citeas-api#51]
While HTTP requests from http://citeas.org/ to http://api.citeas.org/ are fine, HTTP requests from https://citeas.org/ are rejected, because the endpoint isn't secure.

This means that all the API calls from https://citeas.org/ will fail, leaving the app showing an error message.

**Comment by jasonpriem** [comment]
Thanks for the bug report! Fixed. Calls to https://api.citeas.org are now working correctly.
