### ISSUE TITLE
Using words to search?

### ISSUE THREAD

**Issue by jameshowison** [Impactstory/citeas-api#55]
Currently the search bar doesn't suggest using a word, but we have that capability.  Can we add that prompt to the search bar (next to ArXiv ID)?

Also I think we just use the first search result.  I've been playing around with adding +citation to the search term, and I think it might work better in general?

**Comment by caseydm** [comment]
This search bar now says 'keyword' after ArXiv ID. 

Right now we are adding 'software' to every keyword query then returning the first search result. Do you want me to remove that and put citation instead? Maybe try it out for a bit and see how it works?

**Comment by jameshowison** [comment]
Oh ok. Not sure if it makes sense to try both "software" and "citation"
(and maybe "how to cite" or "Requested Citation") as starting points? Could
multiple starting points be fed into the provenance process?

Also any reason why not "or any search term (e.g.. software
name/abbreviation)" rather than "keyword"? Keyword implies some controlled
vocab or something?

--James

**Comment by caseydm** [comment]
Good point. Just updated the search term language again.

No, right now the search portion happens at the beginning of the process so I don't think we can change search terms by provenance (without a lot of refactoring). I'll add 'software' and 'citation' to the current search terms and we can see how that performs for a bit.
