### ISSUE TITLE
Use CITATION file from repository

### ISSUE THREAD

**Issue by ethanwhite** [Impactstory/citeas-api#6]
~4 years ago there was a push to make finding the correct software citation easier by including a CITATION file in the repo: https://www.software.ac.uk/blog/2013-09-02-encouraging-citation-software-introducing-citation-files

E.g., we have on here: https://github.com/weecology/retriever/blob/master/CITATION

These don't appear to currently being used.

There does appear to be quite a lot of variation, e.g., here's one from a @ctb project: https://github.com/dib-lab/khmer/blob/master/CITATION

which maybe makes them difficult to use, but I thought I'd mention it. It might be possible to at least look for a bibtex citation inside the files.

**Comment by ethanwhite** [comment]
And never mind. You are finding it already. Sorry for the noise. I was thrown off by it being call `R CITATION FILE`

**Comment by hpiwowar** [comment]
Yeah that makes sense.  Have modified the "R CITATION" to just "CITATION" and added your blog post as a resource when describing them.  Thanks Ethan!
