### ISSUE TITLE
For R packages, use publication date from DESCRIPTION 

### ISSUE THREAD

**Issue by hadley** [Impactstory/citeas-api#8]
e.g. http://citeas.org/cite/https://cran.r-project.org/web/packages/tidyr has "(n.d.)" but in https://cran.r-project.org/web/packages/tidyr/DESCRIPTION you could take the year from the Date/Publication field.

**Comment by hpiwowar** [comment]
good idea.

**Comment by caseydm** [comment]
This is now working properly.
