### ISSUE TITLE
Some R packages contain ORCID ids

### ISSUE THREAD

**Issue by hadley** [Impactstory/citeas-api#9]
e.g. https://cran.r-project.org/web/packages/usethis/DESCRIPTION

Maybe you already know about this, or maybe there's no obvious way to use it, but I thought you might like to know about it.

**Comment by hpiwowar** [comment]
thanks!  yeah, we sometimes get ORCID data back from Crossref too, when people want us to cite a paper.  

No obvious way to use it though since it isn't included as a standard part of citation formats.
